/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI2_JAVA_SWING;

import javax.swing.ButtonGroup;

/**
 *
 * @author Dungna89
 */
public class B3_JFrame_Tong_Hop extends javax.swing.JFrame {

  /**
   * Creates new form B3_JFrame_Tong_Hop
   */
  public B3_JFrame_Tong_Hop() {
    initComponents();
    radioButton();
  }
  void radioButton(){
    //Hành động code dưới đây giúp cho người dùng chỉ có thể chọn 1 trong 3
    ButtonGroup groupGioiTinh = new ButtonGroup();
    groupGioiTinh.add(rdb_Nam);
    groupGioiTinh.add(rdb_Nu);
    groupGioiTinh.add(rdb_KhongXacDinh);
    rdb_KhongXacDinh.setSelected(true);
    
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbl_ChaoBan = new javax.swing.JLabel();
    txt_InputTen = new javax.swing.JTextField();
    btn_OK = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    rdb_Nam = new javax.swing.JRadioButton();
    rdb_Nu = new javax.swing.JRadioButton();
    rdb_KhongXacDinh = new javax.swing.JRadioButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbl_ChaoBan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    lbl_ChaoBan.setText("Chào bạn.....");
    lbl_ChaoBan.setToolTipText("");

    txt_InputTen.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    btn_OK.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_OK.setText("OK");
    btn_OK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_OKActionPerformed(evt);
      }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel2.setText("Nhập tên:");
    jLabel2.setToolTipText("");

    rdb_Nam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    rdb_Nam.setText("NAM");

    rdb_Nu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    rdb_Nu.setText("NỮ");

    rdb_KhongXacDinh.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    rdb_KhongXacDinh.setText("Không xác định");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(60, 60, 60)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbl_ChaoBan)
          .addGroup(layout.createSequentialGroup()
            .addComponent(txt_InputTen, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_OK)
            .addGap(18, 18, 18)
            .addComponent(rdb_Nam)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rdb_Nu)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rdb_KhongXacDinh)))
        .addContainerGap(219, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_InputTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_OK)
          .addComponent(jLabel2)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(rdb_Nam)
            .addComponent(rdb_Nu)
            .addComponent(rdb_KhongXacDinh)))
        .addGap(18, 18, 18)
        .addComponent(lbl_ChaoBan)
        .addContainerGap(641, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed
   String name = txt_InputTen.getText();///Lấy value do người dùng nhập
   lbl_ChaoBan.setText("Chào bạn " + name + " học môn JAVA2");
  }//GEN-LAST:event_btn_OKActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(B3_JFrame_Tong_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(B3_JFrame_Tong_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(B3_JFrame_Tong_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(B3_JFrame_Tong_Hop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new B3_JFrame_Tong_Hop().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_OK;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel lbl_ChaoBan;
  private javax.swing.JRadioButton rdb_KhongXacDinh;
  private javax.swing.JRadioButton rdb_Nam;
  private javax.swing.JRadioButton rdb_Nu;
  private javax.swing.JTextField txt_InputTen;
  // End of variables declaration//GEN-END:variables
}
