/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI_TAP_MAU_CRUD_SINHVIEN;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dungna89
 */
public class Main_GUI extends javax.swing.JFrame {
  IStudentService _iStudentService;
  DefaultTableModel _defaultTableModel;
 
  public Main_GUI() {
    initComponents();
    _iStudentService = new StudentService();   
    cbcGioiTinh();
  }
  void cbcGioiTinh() {
    DefaultComboBoxModel dcbb = new DefaultComboBoxModel();
    dcbb.addElement("Nam");
    dcbb.addElement("Nữ");
    dcbb.addElement("Không xác định");
    cbc_sex.setModel(dcbb);
  }
  Student getDataStudent(){
    return new Student(txt_msv.getText(), (rdb_Mob.isSelected()?"MOB":rdb_udpm.isSelected()?"UDPM":"WEB"),
            _iStudentService.getMaxID(), txt_ten.getText(), txt_sdt.getText(),
            cbc_sex.getSelectedItem().toString().equals("Nam")?1:0);
  }
  void loadTable(){
    if (_iStudentService.getLstStudent().isEmpty()) {
      JOptionPane.showMessageDialog(this, "Không có dữ liệu");
      return;
    }
    _defaultTableModel = (DefaultTableModel) tbl_sinhvien.getModel();
    _defaultTableModel.setRowCount(0);//Loại bỏ 4 dòng trắng
    int stt = 1;
    for (Student x : _iStudentService.getLstStudent()) {
      _defaultTableModel.addRow(new Object[]{stt++,x.getId(),x.getTen(),x.getSdt(),x.getMsv(),
        x.getNganhHoc(),x.getGioiTinh() == 1?"Nam":"Nữ"});
    }    
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel8 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    txt_Id = new javax.swing.JTextField();
    rdb_Mob = new javax.swing.JRadioButton();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    cbc_sex = new javax.swing.JComboBox<>();
    jLabel12 = new javax.swing.JLabel();
    btn_xoa = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    txt_ten = new javax.swing.JTextField();
    txt_sdt = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    txt_msv = new javax.swing.JTextField();
    rdb_udpm = new javax.swing.JRadioButton();
    rdb_web = new javax.swing.JRadioButton();
    btn_fakeData = new javax.swing.JButton();
    btn_sua = new javax.swing.JButton();
    btn_them = new javax.swing.JButton();
    btn_tim = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbl_sinhvien = new javax.swing.JTable();
    txt_timkiem = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel8.setText("Msv:");

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setText("ID:");

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel9.setText("btn");

    txt_Id.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    rdb_Mob.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    rdb_Mob.setText("MOB");

    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel10.setText("txt");

    jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel11.setText("rdb");

    cbc_sex.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    cbc_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel12.setText("cbc");

    btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_xoa.setText("Xóa");

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel2.setText("Quản lý sinh viên FPOLY SP22");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel3.setText("Tên: ");

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel4.setText("Sđt:");

    txt_ten.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    txt_sdt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel5.setText("lbl");

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel6.setText("Ngành:");

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel7.setText("Sex:");

    txt_msv.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    rdb_udpm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    rdb_udpm.setText("UDPM");

    rdb_web.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    rdb_web.setText("WEB");

    btn_fakeData.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_fakeData.setText("Fake Data");
    btn_fakeData.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_fakeDataActionPerformed(evt);
      }
    });

    btn_sua.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_sua.setText("Sửa");

    btn_them.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_them.setText("Thêm");
    btn_them.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_themActionPerformed(evt);
      }
    });

    btn_tim.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_tim.setText("Tìm");

    tbl_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null}
      },
      new String [] {
        "STT", "ID", "TÊN", "SĐT", "MSV", "NGÀNH HỌC", "SEX"
      }
    ));
    jScrollPane1.setViewportView(tbl_sinhvien);

    txt_timkiem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(81, 81, 81)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel3)
                      .addComponent(jLabel1)
                      .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(txt_sdt)
                      .addComponent(txt_ten)
                      .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(btn_fakeData)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btn_them)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(btn_sua)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btn_xoa)
                    .addGap(271, 271, 271))
                  .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(jLabel6)
                      .addComponent(jLabel7)
                      .addComponent(jLabel8))
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(cbc_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                          .addComponent(txt_msv, javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(rdb_Mob)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rdb_udpm)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_web))))))
              .addGroup(layout.createSequentialGroup()
                .addComponent(btn_tim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel10)
                  .addComponent(jLabel5)
                  .addComponent(jLabel11)
                  .addComponent(jLabel9)
                  .addComponent(jLabel12)))))
          .addGroup(layout.createSequentialGroup()
            .addGap(244, 244, 244)
            .addComponent(jLabel2)))
        .addContainerGap(57, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txt_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6)
          .addComponent(rdb_Mob)
          .addComponent(rdb_udpm)
          .addComponent(rdb_web))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7)
          .addComponent(cbc_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_fakeData)
          .addComponent(btn_them)
          .addComponent(btn_sua)
          .addComponent(btn_xoa))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_tim)
          .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel12)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_fakeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fakeDataActionPerformed
    _iStudentService.fakeData();
    loadTable();
  }//GEN-LAST:event_btn_fakeDataActionPerformed

  private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
    _iStudentService.add(getDataStudent());
    loadTable();
  }//GEN-LAST:event_btn_themActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main_GUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_fakeData;
  private javax.swing.JButton btn_sua;
  private javax.swing.JButton btn_them;
  private javax.swing.JButton btn_tim;
  private javax.swing.JButton btn_xoa;
  private javax.swing.JComboBox<String> cbc_sex;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JRadioButton rdb_Mob;
  private javax.swing.JRadioButton rdb_udpm;
  private javax.swing.JRadioButton rdb_web;
  private javax.swing.JTable tbl_sinhvien;
  private javax.swing.JTextField txt_Id;
  private javax.swing.JTextField txt_msv;
  private javax.swing.JTextField txt_sdt;
  private javax.swing.JTextField txt_ten;
  private javax.swing.JTextField txt_timkiem;
  // End of variables declaration//GEN-END:variables
}
